### ISSUE TITLE
saveFile function

### ISSUE THREAD

**Issue by gsustalo** [vitogit/gDriveSync.js#3]
Hi,I would like to know how to invoke the saveFile function.

My purpose is to upload a file (pdf) to drive from local.

Could you explain the parameters that are passed to saveFile?

Thank you

**Comment by vitogit** [comment]
Hi, currently this library don´t support that kind of files. It works mostly with text documents that you know the content to upload. If somehow you could read the file content you could try the `saveFileRaw` method. Here is an example and parameters:

https://github.com/vitogit/gDriveSync.js/blob/6063b5fbb34fd815760872346bfa490251821a32/demo/index.html#L88
